sudo: required
notifications:
  email:
    on_success: always
    on_failure: always
  slack:
    slack: srboeingdotnet:t39kVEYScX7icPbJaaBlkSge
language: node_js
node_js:
- node
os:
- linux
install:
- npm install
script:
- npm run lint
- npm run test
